FROM python:3.7-slim

RUN mkdir /app

COPY api_yamdb/requirements.txt /app

RUN pip install --upgrade pip

RUN pip3 install -r api_yamdb/requirements.txt --no-cache-dir

COPY api_yamdb/ /app

WORKDIR /app

CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "0:8000" ] 

